# Generated by Django 2.2.10 on 2020-08-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_admin_bills_bookings_customer_orders_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
