# Generated by Django 2.2.10 on 2020-08-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
