# Generated by Django 2.2.10 on 2020-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_guestprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(default=101, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_number',
            field=models.CharField(default='101', max_length=3),
            preserve_default=False,
        ),
    ]
