# Generated by Django 2.2.10 on 2020-08-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200824_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aadhaar_number',
            new_name='aadhar_number',
        ),
    ]
