# Generated by Django 2.2.10 on 2020-09-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_adminprofile_bills_foodservices_guestprofile_laundryservice_menuitems_room_roomservices_services_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='room_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Room'),
        ),
    ]
