# Generated by Django 2.2.10 on 2020-09-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200901_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Room'),
        ),
    ]
