# Generated by Django 2.2.10 on 2020-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200901_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='user_room_number',
            field=models.CharField(default=101, max_length=3),
            preserve_default=False,
        ),
    ]
