# Generated by Django 2.2.10 on 2020-09-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200902_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='payment_type',
            field=models.CharField(default='Cash', max_length=100),
            preserve_default=False,
        ),
    ]
