# Generated by Django 2.2.10 on 2020-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_bills_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='room_number',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
