# Generated by Django 3.0.6 on 2020-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_userprofile_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodservices',
            name='message',
        ),
        migrations.AddField(
            model_name='foodservices',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
    ]
