# Generated by Django 3.0.6 on 2020-09-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200904_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodservices',
            old_name='available_status',
            new_name='status',
        ),
    ]
