# Generated by Django 3.0.6 on 2020-09-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200904_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Services'),
        ),
    ]
