# Generated by Django 3.0.6 on 2020-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20200904_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodservices',
            name='where',
            field=models.CharField(default=101, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodservices',
            name='menu_item',
            field=models.CharField(max_length=100),
        ),
    ]
