# Generated by Django 2.2.10 on 2020-09-06 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_restaurantorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
