# Generated by Django 2.2.10 on 2020-09-06 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20200906_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorders',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
