# Generated by Django 2.2.10 on 2020-09-06 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_restaurantorders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
