# Generated by Django 2.2.10 on 2020-09-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20200906_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tables'),
        ),
    ]
